
name: Github action for your deployment
on:
    push:
      branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10.4
          uses: actions/setup-python@v3
          with:
            python-version: 3.10.4
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then
                pip install -r requirements.txt
            else 
                pip freeze > requirements.txt
            fi
        - name: Creting a Dockerfile
          run: |
            echo "
              FROM python:3.10.4
              WORKDIR /app
              COPY . .
              RUN pip3 install -r requirements.txt
              CMD ["python3", "src/app.py"]
              " > Dockerfile

        - name: Docker login
          uses: docker/login-action@v1 
          with:
            registry: registry.patr.cloud
            username: ashish-oli
            password: ${{ secrets.REGISTRY_PASSWORD }}

        - name: Build image from Dockerfile and push to patr-registry
          run: |
            docker build . -t ashish-oli/deployment
            docker tag ashish-oli/deployment registry.patr.cloud/personal-workspace-1424404d9fff474bba7f23825681f6a8/flask:latest 
            docker push registry.patr.cloud/personal-workspace-1424404d9fff474bba7f23825681f6a8/flask:latest
